### ISSUE TITLE
M5STACK-minimed-monitor

### ISSUE THREAD

**Issue by AlejandroPaula** [ondrej1024/m5-minimed-monitor#1]
Hi, I am trying to implement in v Code and I am stuck, could you do a little tutorial on how to implement it ?. If you do not mind.

**Comment by ondrej1024** [comment]
What is "v Code"? Do you mean Visual Studio Code? I am afraid I don't have a tutorial for that. 
I am using [Thonny](https://thonny.org/) as development environment which allows to write the source code and run it directly on the M5Stack Core2. Also you can write the application and image files to the Core2 flash memory with Thonny. It's very easy to use.

**Comment by AlejandroPaula** [comment]
Could you tell me how Tonny is used with a short explanation?  If you do not mind?

**Comment by ondrej1024** [comment]
Did you perform the steps described in the [Installation chapter](https://github.com/ondrej1024/m5-minimed-monitor#installation) of the readme ? Where do you get stuck?

**Comment by AlejandroPaula** [comment]
Yes, I've read it, I've done the Uiflow firmware thing, and I'm stuck on how to load and mount the app on Tonny.  I do not have much experience in this I have tried to mount it but I do not succeed, if you can tell me how to add in Tonny

**Comment by AlejandroPaula** [comment]
I am here, how to clone the git that you have created to mount it?

**Comment by AlejandroPaula** [comment]
![IMG20210701140026](https://user-images.githubusercontent.com/39844024/124128916-26af8d00-da75-11eb-89fa-bcbfdd8c8d9c.jpg)

**Comment by ondrej1024** [comment]
The first thing to do is get the Python console on your Core2. 

To do that you connect the Core2 via USB cable and set it to USB mode you. Then you need to choose the interpreter "MicroPython (ESP32)" and the USB port in the Thonny settings (see picture).

![image](https://user-images.githubusercontent.com/5494041/124135552-32ef1680-da84-11eb-8a49-3a0d45296bd6.png)

It looks like you have a different Thonny version. I am using 3.2.7.

**Comment by AlejandroPaula** [comment]
Are you referring to this?  (Microphyton)

**Comment by AlejandroPaula** [comment]
![Uploading IMG20210701151141.jpg…]()

**Comment by AlejandroPaula** [comment]
Ok
![IMG_20210701_154329](https://user-images.githubusercontent.com/39844024/124143562-21593f00-da83-11eb-9310-28625c530999.jpg)
, I've done it, now I don't know what else I should do to add Minimed-mon.py and res

**Comment by ondrej1024** [comment]
OK, that's great.
Now you should clone the m5-minimed-monitor repository with the GIT tool of your choice (it cannot be done with Thonny). After that you can open minimed-mon.py in Thonny.

**Comment by AlejandroPaula** [comment]
Ahora q debo hacer?
![Uploading IMG20210701155741.jpg…]()

**Comment by AlejandroPaula** [comment]
![IMG20210701155741](https://user-images.githubusercontent.com/39844024/124146662-e4db1280-da85-11eb-8dec-d881d89ce9ea.jpg)

**Comment by ondrej1024** [comment]
Do you know how to clone a Git repository to your PC ?

**Comment by AlejandroPaula** [comment]
Como se hace?

**Comment by ondrej1024** [comment]
There must be a lot of guides and tutorials for GIT on the web. But to put it simple: if you just want to download the code click on the Code button on the repository web page and download the zip file.
![image](https://user-images.githubusercontent.com/5494041/124148060-95014900-da8f-11eb-98c4-88ad7e4fbe84.png)

**Comment by AlejandroPaula** [comment]
![IMG20210701162008](https://user-images.githubusercontent.com/39844024/124149177-400e0480-da88-11eb-96e9-7af87b7686b6.jpg)
Es esto? Lo siento pero estoy bastante perdido.

**Comment by ondrej1024** [comment]
If you don't get the green "RUN" button you should try to red "STOP" button first. You can also try hitting CTRL-C in the console window. Just play with it and you'll find a way.

**Comment by AlejandroPaula** [comment]
![IMG20210701163113](https://user-images.githubusercontent.com/39844024/124150930-f0303d00-da89-11eb-8ca7-ed95471f68c6.jpg)
Aqui debo cambiar algo más sin ser la WIFI y contraseña?

**Comment by AlejandroPaula** [comment]
Q debo poner en ?:
PROXI_SERVER=
PROXI_PORT=
NTP_SERVER=

**Comment by AlejandroPaula** [comment]
No se cómo avanzar😥

**Comment by ondrej1024** [comment]
> Q debo poner en ?:
> PROXI_SERVER=
> PROXI_PORT=
> NTP_SERVER=

Just read the comments in the code and the "Project Status":

_The main drawback, at the moment, is that the Carelink Python Client, which is responsible for downloading the Minimed pump and sensor data from the Carelink Cloud server, is not yet integrated into the Core2 device as this requires a porting of the client code to Micro Python. Therefore I have an external carelink_client_proxy running on a separate device which is on 24h a day and provides the data to the Core2 in the LAN via a very simple REST API._

**Comment by AlejandroPaula** [comment]
Entonces para poder usar el M5STACK es necesario otro dispositivo ( por ejemplo una Raspberry pi4) conectado 24h para q envié los datos a M5STACK? Es así?

**Comment by ondrej1024** [comment]
I don't understand spanish but I _assume_ the answer is yes.

**Comment by AlejandroPaula** [comment]
Excuse me for not translating .. So to be able to use the M5STACK is it necessary another device (for example a Raspberry pi4) connected 24h to send the data to M5STACK?  Is it so?
 If it is correct, how could I do it?  I also have a Raspberry Pi4

**Comment by ondrej1024** [comment]
You need the carelink-python-proxy on an external device to download the data from Carelink. Then the m5-minimed-monitor running on the Core2 can download it from the proxy.

Just follow the instructions in this repository and in [carelink-python-client](https://github.com/ondrej1024/carelink-python-client). If this is not clear enough study the code to find out how everything works. I can't give step by step instructions, don't have time for that, sorry.

**Comment by AlejandroPaula** [comment]
Thank you very much for your time.
