### ISSUE TITLE
missing mm_banner_delivery_suspend.png

### ISSUE THREAD

**Issue by sj0er-D** [ondrej1024/m5-minimed-monitor#2]
first of all, great work! been trying to install the script on my m5, but ran into the issue that mm_banner_delivery_suspend.png was not in the RES folder. I added a bogus one myself to see if the app loads on my m5, and unfortunately it does not load further. I will troubleshoot why not, but could. you please add the mentioned image?
After adding mm_banner_delivery_suspend.png and the icon_mmm.png to the res folder, it did make the PC version work.

**Comment by ondrej1024** [comment]
Thanks for reporting this. I actually forgot to version some icons. They have been added now in the master branch. Let me know if things are running smooth now.

**Comment by sj0er-D** [comment]
The banner shows now, and there is no error on the image anymore, but... it now shows an error on line 347:

Traceback (most recent call last):
  File "main.py", line 347, in <module>
NameError: name 'FONT_MONT_16' isn't defined

Any ideas?

Also, in NL, we use mmol/L for the sg/bg values. I can already see on my proxy logs that the value for 'SG' is shared by carelink in mg/dL. In order to get it to mmol/L, it needs to be multiplied by 0.0555 (sg*0.0555=mmol/L value). It's easy to find/replace 'mg/dL' --> 'mmol/L' for the labels, but i could use some help with embedding a calculation that outputs the sg in mmol/L (excuse me for this, i am just starting in the world of Python).

**Comment by sj0er-D** [comment]
I've checked the pc python code on my mac and it runs nicely by the way.

**Comment by sj0er-D** [comment]
Ok, checked again myself and changed some font sizes and positioning. it works now!

`# Init labels on screen 1
labelBglValue    = M5Label('--', x=140, y=90, color=0xffffff, font=FONT_MONT_48, parent=scr1)
labelBglUnit     = M5Label('mg/dL', x=137, y=145, color=0x89abeb, font=FONT_MONT_18, parent=scr1)
labelActInsValue = M5Label('-- U', x=251, y=173, color=0xffffff, font=FONT_MONT_26, parent=scr1)
labelActIns      = M5Label('Act Insulin', x=221, y=200, color=0xffffff, font=FONT_MONT_18, parent=scr1)
labelTime        = M5Label('--:--', x=250, y=0, color=0xffffff, font=FONT_MONT_26, parent=scr1)
labelLastData    = M5Label('--', x=120, y=218, color=0xffffff, font=FONT_MONT_18, parent=scr1)
labelSage        = M5Label('', x=144, y=8, color=0xffffff, font=FONT_MONT_14, parent=scr1)`

Only thing left to do for me is to relabel/calculate mg/dL to mmol/L

**Comment by ondrej1024** [comment]
Great. 

As for the fonts, you might have a different UIFLOW firmware version on your Core2 and they might have changed some font names.

Regarding the SG unit, the Minimed API reports the unit which your system uses in this parameter:

`
bgUnits: "MGDL"
`

At the moment M5 Minimed Monitor does not check this values but just uses mg/dL hard coded. This is something which still needs to be implemented. Then you can probably configure the unit you wish to use in your Carelink account and it should appear correctly.

For now you can convert the mg/dl value into mmol in line 645 of minimed-mon.py:

```
lastSG = r.json()["lastSG"]["sg"] * 0.0555 # convert to mmol
lastSG = round(lastSG,1)                   # round to 1 decimal
```

**Comment by sj0er-D** [comment]
Simply amazing! I changed it, and it works flawless! thanks!
